[package]
name = "harbor-vulns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
reqwest = "0.12.5"
thiserror = "1.0.63"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.128"
